#!/bin/bash

if [ ! -x /media/wd_media/backup ]
then
    sudo mount /media/wd_media 2>/dev/null
    if [  $? -nq 0 ]
    then
        echo "ERROR - Could not mount wd passport external hard disk !"
        exit 2
    fi
fi

    rsync -aR --exclude /home/jeremyb/devel/linux/ /home/jeremyb/devel/ /media/wd_media/backup/
    rsync -aR  /home/jeremyb/private/  /media/wd_media/backup/
    rsync -aR  /home/jeremyb/mail/starred  /media/wd_media/backup/
    rsync -aR  /home/jeremyb/bin/  /media/wd_media/backup/
    rsync -aR  /home/jeremyb/.bashrc  /media/wd_media/backup/
    rsync -aR  /home/jeremyb/.bash_profile  /media/wd_media/backup/
    rsync -aR  /home/jeremyb/.irssi/  /media/wd_media/backup/
    rsync -aR  /home/jeremyb/.vimrc  /media/wd_media/backup/
    rsync -aR  /home/jeremyb/.git/  /media/wd_media/backup/
    rsync -aR  /home/jeremyb/.gitconfig  /media/wd_media/backup/
    rsync -aR  /home/jeremyb/.ssh/  /media/wd_media/backup/
    rsync -aR  /home/jeremyb/.procmailrc  /media/wd_media/backup/
    rsync -aR  /home/jeremyb/.procmail  /media/wd_media/backup/
    rsync -aR  /home/jeremyb/.fdm.conf  /media/wd_media/backup/
    rsync -aR  /home/jeremyb/.addressbook  /media/wd_media/backup/
    rsync -aR  /home/jeremyb/.pinerc  /media/wd_media/backup/
    rsync -aR  /home/jeremyb/.plan  /media/wd_media/backup/
    rsync -aR  /home/jeremyb/.fetchmailrc  /media/wd_media/backup/
    rsync -aR  /home/jeremyb/.perltidyrc  /media/wd_media/backup/
    rsync -aR  /home/jeremyb/.orange.pcf  /media/wd_media/backup/
    rsync -aR  /home/jeremyb/.OBB-VPN.pcf /media/wd_media/backup/
    rsync -aR  /home/jeremyb/.screenrc  /media/wd_media/backup/
    rsync -aR  /home/jeremyb/.mutt  /media/wd_media/backup/
    rsync -aR  /home/jeremyb/.mplayer  /media/wd_media/backup/
    rsync -aR  /home/jeremyb/.mozilla  /media/wd_media/backup/
    rsync -aR  /home/jeremyb/.lan  /media/wd_media/backup/
    rsync -aR  /home/jeremyb/.vim/  /media/wd_media/backup/
    rsync -aR  /home/jeremyb/.synergy.conf  /media/wd_media/backup/

    echo "INFO - Backup done on wd passport external hard disk !"
