#!/bin/bash

string=`echo $1 | tr -d \\x`

i=1
max=$(( ${#string} + 1 ))

while [ $i -lt $max ]
do
        hex='\x'`echo $string | cut -c $i-$(( i + 1 ))`
        strhex=$strhex$hex
        i=$(( i + 2 ))
done
echo -e $strhex
