#!/bin/bash
echo "Number of connections per IP..."
##cut -b 49-75 /tmp/netstat.txt | grep -o -P "\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b" | sort | uniq -c | sort -n -r -k 1,7 | head -10
cut -b 45-68 /tmp/netstat.txt | awk -F':' '{print $1}' | grep '[0-9]*[0-9]*[0-9][.][0-9]*[0-9]*[0-9][.][0-9]*[0-9]*[0-9]'  |sort | uniq -c | sort -n -r -k 1,7 | head -10
