#!/bin/bash
tar -cvf /var/tmp/dotfiles.tar \
/home/jeremyb/.ssh \
/home/jeremyb/.tin \
/home/jeremyb/.vimrc \
/home/jeremyb/.bash_profile \
/home/jeremyb/.bashrc \
/home/jeremyb/.vim \
/home/jeremyb/.nzbfetcher \
/home/jeremyb/.tmux.conf \
/home/jeremyb/.irssi \
/home/jeremyb/.fdm.conf \
/home/jeremyb/.newsauth \
/home/jeremyb/.conkyrc \
/home/jeremyb/.readme \
/home/jeremyb/.gitconfig \
/home/jeremyb/.gitignore \
/home/jeremyb/.screenrc \

