#!/usr/bin/env bash
REMOTE=${1:-"origin"}

if [ -f $HOME/bin/common-func ];then
    source $HOME/bin/common-func
else
    exit 2
fi

CURRENT=`git branch | grep '\*' | awk '{print $2}'`
log "INFO" "Checkout the master branch..."
git checkout master
log "INFO" "Merge the working branch into the master branch..."
git merge ${CURRENT}
log "INFO" "Push the changes to the $REMOTE repository..."
git push $REMOTE master
git checkout ${CURRENT}


