#!/bin/sh -x
# git name-rev is fail
CURRENT=`git branch | grep '\*' | awk '{print $2}'`
echo "INFO: ship: Checkout the master branch..."
git checkout master
echo "INFO: ship: Merge the working branch into the master branch..."
git merge ${CURRENT}
echo "INFO: ship: Push the changes to the origin repository..."
git push origin master
git checkout ${CURRENT}


